### ISSUE TITLE
Thanks for this, what's the license

### ISSUE THREAD

**Issue by msj2** [cherishsantosh/reactNativeLoginWithMediawikiAPI#1]
Hi Santosh, Thanks for building this?
Please specify what's the license for this?

If it's MIT, so that we can freely attribute & fork?
Thanks,
Mallikarjuna.

--Update: Thanks. Super swift repsonse. :)

**Comment by cherishsantosh** [comment]
@msj2 license is create. Please check.

Thanks,
Santosh Shinagre
